### PR TITLE
Trophy Theme

### PR DESCRIPTION
**Pull request by adamclifford**
This is a first pass at adding the trophy theme to the blog recipie

### CODE REVIEW

**Comment by daveaglick** [comment]
Sorry for the delay, finally ready to circle back around to this one. I'm having some trouble getting it to build for my site though. Any change you could take another look now that the changes to the recipes are done?

**Comment by adamclifford** [comment]
I've fixed the issue with the initial config casing an error. I was missing adding in a default dictionary.

You can add additional social media links to the bottom of the page with font awesome icons like this

`Settings["SocialMedia"]}
    {"facebook","http://www.facebook.com/adamclifford"},
    {"twitter", "http://www.twitter.com/adamclifford"}
}`

**Comment by daveaglick** [comment]
Awesome! I can get it to build without any problems, and it looks really, really great. Just have a couple comments/questions (all up for discussion):

* Not sure I like the random placeholder images in the archive when the post doesn't have an image of it's own. Can we just show those posts without an image. Same for the actual post page. And the archive/tags pages for the large banner image when hovering over a post. In general, would you be cool with turning off random placeholder images (maybe show a default gradient image or something instead)?

* There is some strange text wrapping going on in archive/tag pages for some of the posts:

2017-09-09_21h58_53

* I don't see the lead text anywhere - can that be added to the archive and post pages if the post has a lead?

* The site title and intro look like they're being displayed on every non-post page and probably shouldn't be:

2017-09-09_22h03_01

* I really like what you did with the hamburger menu for navigation, especially since that wasn't part of the original theme

* I also love the theme-specific setting for social links - letting the themes branch off with some extra theme-specific customization is something I want to push more

**Comment by adamclifford** [comment]
I have removed teh random images, and there is now just royalty free image that I am using for the default blog image.

I think I have fixed the archaive/tag pages layout. However, if i could get a coppy of your markdown files, I could use them for testing.

The lead text has been added to the archive page. does it need adding to the post page? Maybe under the title?

I have removed the title and intro from other pages.

**Comment by daveaglick** [comment]
Awesome, thanks! Happy we could get this in before the 1.0 release. I'll merge it now and make some final tweaks.

**Pull request merged**
