### PR TITLE
Replace ImageProcessor with ImageSharp in Wyam.Images

### PR DESCRIPTION
**Pull request by MisinformedDNA**
Converts to netstandard2.0

Contributes to #300 

**Do not merge** 

- All code is not ported as I couldn't always find an equivalent. I'm blocked on various pieces of code.
- The code is not tested as there are no tests and, honestly, I'm new here and don't know how yet.

Just wanted to help move us to .NET Standard by moving to the new, specified image processor. This is the beginning, but more work needs to be done... and I need help.

I'm also not an "image guy", so please give as much feedback as you can!

### CODE REVIEW

**Comment by daveaglick** [comment]
Thanks a bunch for starting on this one. I'm taking a look to see if I can unblock some of the differences.

**Comment by daveaglick** [comment]
Got pretty far on this. I ended up basically totally refactoring the module (though the old code and your fixes we very helpful). Hopefully I'll have something to show for it tomorrow - still need to add some tests.

**Comment by daveaglick** [comment]
All done. There's some breaking changes for anyone using the module, though basically all the old functionality is still available one way or another.

I added some simple tests to be sure ImageSharp isn't crashing and the output paths are as expected, but I have no idea how to actually tests the output so that'll have to do for now. I'll be on the lookout for bug reports when this goes out.

**Comment by JimBobSquarePants** [comment]
>I have no idea how to actually tests the output so that'll have to do for now. 

I would simply guard yourself against regression and trust us to handle anything more complicated.

Generate a set of reference images using the library now and if they look correct, use them to compare against in the future.

**Comment by daveaglick** [comment]
Thanks, great advice @JimBobSquarePants! I’m always happy to make things someone else’s problem :smile:

**Pull request merged**
