### PR TITLE
Add "RssGuid" as a "magic" meta key which generates the Guid.  Fluent…

### PR DESCRIPTION
**Pull request by deanebarker**
… method "WithGuidMetaKey" will allow the specification of this key.

### CODE REVIEW

**Comment by daveaglick** [comment]
Did you mean to close this?

**Comment by daveaglick** [comment]
I was literally about to merge it before heading out for the day - if you submit another PR, I'll get it merged tonight :)

**Comment by deanebarker** [comment]
I don't know how I closed it. I'm not a developer, remember? :-)

**Comment by daveaglick** [comment]
Guess I better merge this quick before you take it back again!

**Pull request merged**
