### PR TITLE
Added Solid State theme

### PR DESCRIPTION
**Pull request by RLittlesII**
PR for #491 that adds the Solid State theme to Wyam.

### CODE REVIEW

**Comment by RLittlesII** [comment]
@daveaglick So.  Why don't my styles propagate?  What did I do wrong?

**Comment by daveaglick** [comment]
Been working on this a bit today :smile:. There were a couple bits that broke with the most latest build, so I fixed those (mainly just different pipeline names and moved template files). I also got a little carried away with finishing touches so I can just go ahead and merge this in and release it. I'll commit to the PR first so you can see the changes though.

Should finish up today or tomorrow - thanks!

**Comment by daveaglick** [comment]
Thanks. This pull request has been integrated manually.

**Comment by daveaglick** [comment]
Looks fantastic! I couldn't figure out how to commit to the PR before merging, but you can check out commit https://github.com/Wyamio/Wyam/commit/906eb52b011d70a0cda0ff029141e10949dedf79 to see the changes I made. Considering switching my own blog to this theme when it releases...

**Comment by RLittlesII** [comment]
You cleaned up a lot 😬
Thanks for looking at this.  Apologies if it was messy.  I had no idea what I was doing.  Looking forward to the next release!

**Pull request closed without merging**
