### PR TITLE
[WIP] prefer var over explicit types

### PR DESCRIPTION
**Pull request by ghuntley**
As per @agc93’s tweet: 

https://twitter.com/agc93/status/1115069515782471680?s=09

### CODE REVIEW

**Comment by ghuntley** [comment]
💩

**Comment by vcsjones** [comment]
:shipit: 

Might want to add a comment encouraging use of C# 8's `target type new` as well.

**Comment by daveaglick** [comment]
DF3EC4D5-30C5-41BA-BA22-C5C8DEF06214

**Comment by gep13** [comment]
@daveaglick just testing out my new Chrome Extension: https://chrome.google.com/webstore/detail/gifs-for-github/dkgjnpbipbdaoaadbdhpiokaemhlphep 😄

**Pull request closed without merging**
