### PR TITLE
Issue #443: Add enforcement for style rules

### PR DESCRIPTION
**Pull request by shaneray**
- Added .editorconfig based on rosyln project.
- Added StyleCop.Analyzers nuget package to all projects.

### CODE REVIEW

**Comment by daveaglick** [comment]
So is this going to light up my warnings like a Christmas tree? :christmas_tree:

**Comment by shaneray** [comment]
It will.
image

The thought is, once in place we can start creating issues to correct the specific error codes. (example below)
- Warning	SA1001	Commas must be followed by whitespace.
- Warning	SA1000	The keyword 'if' must be followed by a space.

Then we are able to attack the issues individually and hopefully get some community support as well.  If one of the rules are not valid (Example: Warning SA1101	Prefix local calls with this) we can have a discussion, then update the rules for that item and close the issue.

**Comment by shaneray** [comment]
I just pushed another commit.
After the "usingDirectivesPlacement": "outsideNamespace" setting was applied and I changed SA1633: File must have header to info rather than warning.  We are looking like this.
image
I also added a solution folder with the different style rules to make editing easier.
image
Let me know if you would like me to change anything else.

**Comment by daveaglick** [comment]
Awesome! Didn't quite get to this today, but I'm hoping to pull it in next.

**Comment by phil-scott-78** [comment]
I had a chance to mess around with this and coming up with a sane ruleset. I based the ruleset on how `Wyam.Core` and `Wyam.Common`'s style and went from there. Attached the ruleset I've made so far. Was going to try and write them out, but it's slow going. More or less the big changes made

* don't worry about var
* don't worry about spacing around `()[]{}`
* super relaxed documentation rules
* people that put using statements in namespaces are crazy
* don't worry about the order of methods / fields / etc
* things like using tabs, trailing whitespace, etc all are made info warnings

With that in place the results end up like this and honestly once you see the 100 errors and about 500 info messages that you'll want to correct them all. But I'm not going to be *that guy* who submits a 100 file PR with a bunch of style changes 😄 

image


[Wyam.CodeAnalysis.zip](https://github.com/Wyamio/Wyam/files/788372/Wyam.CodeAnalysis.zip)

**Comment by daveaglick** [comment]
Don't worry about rebasing this PR - I've got it working in a local branch and will mark it as merged once I commit it. Taking a look now - going to tweak the rules a little to my own preference (it's good to be the boss) and I'll probably end up somewhere between what's in this PR and more lightweight ruleset @enkafan has produced (take your var somewhere else, explicit types 4 lyfe).

**Comment by daveaglick** [comment]
Thanks. This pull request has been integrated manually.

**Comment by daveaglick** [comment]
Still going over the rules and refining things, but since it's such a big change to project files and the like I wanted to get it in the develop branch as soon as I was comfortable with it. Going to do several more follow-up commits as I ratchet down some of the requirements, fix problems, etc. At about 5,000 warnings right now.

**Pull request closed without merging**
